# -*- coding: utf-8 -*-
"""2.Face API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzD7lu3bmkSUNxgP_HsyXne2d2a8Bidm
"""

import requests
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

subscription_key = '2b7132593e37491e8597235dbee959fe'
face_api_url = 'https://labuser79face.cognitiveservices.azure.com/face/v1.0/detect'


#Class, library, Package 대문자 관례
#지역변수, 파라메타 소문자로 관례
#addr, msg 줄임말은 배제
#두 단어가 합쳐지면 두 번쨰 단어는 대문자
#상수는 전체가 대문자  const MAX_USER=100

image_url = 'http://image.koreatimes.com/article/2021/05/10/20210510094734601.jpg'

image = Image.open(BytesIO(requests.get(image_url).content))
image

headers = {'Ocp-Apim-Subscription-Key': subscription_key}

params = {
    'returnFaceId': 'false',
    'returnFaceLandmarks': 'false',
    'returnFaceAttributes': 'Smile'
}

data = {'url': image_url}

response = requests.post(face_api_url, params=params, headers=headers,json=data)
faces = response.json()
faces

draw = ImageDraw.Draw(image)

def DrawBox(faces):

  for face in faces:
    rect = face['faceRectangle']
    left = rect['left']
    top = rect['top']
    width = rect['width']
    height = rect['height']

    draw.rectangle(((left,top),(left+width,top+height)),outline='red')

    face_attributes = face['faceAttributes']
    smile = face_attributes['smile']
    draw.text((left,top),str(smile),fill='red')

DrawBox(faces)
image

